name: Fix localisation
on:
  pull_request:
    branches-ignore:
      - 'master'
  push:
    branches-ignore:
      - 'master'
jobs:
  fix_localisation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Fix locs
      uses: The24thDS/stellaris-localisation-crowdin-fix@v1.0.3
      with:
        localisation_folder: 'new_enclaves/localisation'
    - name: Commit files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Autofix for locasisation files"
        git push



