name: Create new release
on:
  push:
    branches:
    - master
    tags:
    - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive New Enclaves
      uses: thedoctor0/zip-release@master
      with:
        filename: 'new_enclaves_v.zip'
        exclusions: '*.git* /*assets/* /*compatibility-patches/* /*addons/* /*steam/* /*vanilla_cache/* .all-contributorsrc README.md crowdin.yml'
    - name: Archive New Enclaves Compatibility Patches
      uses: thedoctor0/zip-release@master
      with:
        filename: 'new_enclaves_compatibility_patches.zip'
        path: 'compatibility-patches/'
    - name: Create release with artifacts
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'new_enclaves_v.zip,new_enclaves_compatibility_patches.zip'
        name: 'New Enclaves v'
        body: 'Available on:\n- Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2356224372'
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
